language: python

sudo: required


before_install:
    - sudo apt update -qq

install:
    - pip install ansible

script:
    - ansible --version
    - ip a s
    - ansible-playbook  -connection=local 127.0.0.1 playbook.yml