dist: bionic

services:
    - docker

before_install:
    - docker pull python:latest
    - docker run -itd -v $(pwd):/ --name mypython python:latest
    - docker ps
     

script:
    - docker exec -it mypython /bin/bash "python second.py"
